Use Case Common [Register] : Verify Email Token
f-lab-edu/YouAndMe pull request #29
Opened 2021-09-04 08:30 UTC by JiwonDev

#8 Resolves.

2021-09-04 08:40 UTC, Rebwon commented on src/test/java/com/yam/app/account/domain/FakeAccountRepository.java
> +@Component
Fake 구현체인데, Component 등록을 해야할 이유가 있을까요?

2021-09-04 08:45 UTC, Rebwon requested changes
중첩 테스트로 분리하신 점이 인상적입니다.

2021-09-04 08:45 UTC, Rebwon commented on src/test/java/com/yam/app/account/domain/TokenVerifierTest.java
> +
일관성을 위해서 공백은 제거해주세요.

2021-09-04 08:45 UTC, Rebwon commented on src/test/java/com/yam/app/account/infrastructure/MybatisAccountRepositoryTest.java
> +        account.completeRegister(); // boolean emailVerified = true
안의 내부 구현을 주석으로 보여주는 것은 바람직하지 않은 것 같습니다.

2021-09-04 08:45 UTC, Rebwon commented on src/test/java/com/yam/app/account/presentation/AccountCommandApiTests.java
> +    @Nested
테스트를 중첩으로 변경하셨군요. 👍👍

2021-09-04 08:45 UTC, Rebwon commented on src/test/java/com/yam/app/account/presentation/AccountCommandApiTests.java
> +            // Arrange
Arrange 절에 아무 것도 없다면 삭제하셔도 됩니다.

2021-09-04 14:25 UTC, f-lab-dev commented on src/main/java/com/yam/app/account/domain/TokenVerifier.java
> +    public boolean verify(String token, String email) {
토큰 검증을 하는 곳에서 `completeRegister`를 호출하여 토큰 검증뿐 아니라 가입완료 처리까지 해주고 있습니다.

토큰 유효성 검사화 함께 가입완료처리까지 두 가지 책임을 준 이유가 있으실까요?

2021-09-04 14:25 UTC, f-lab-dev commented on src/main/java/com/yam/app/account/infrastructure/MybatisAccountRepository.java
> +        int result = template.update(COMMAND_NAMESPACE + "update", entity);
`COMMAND_NAMESPACE + "update"`처럼 문자열 조립으로 처리하면 실수의 여지가 생길 것 같습니다~

2021-09-04 14:25 UTC, f-lab-dev commented on src/main/java/com/yam/app/account/domain/TokenVerifier.java
> +    public boolean verify(String token, String email) {
그리고 이 메소드는 유효성 검사를 한 후에, 맞지 않으면 예외를 던져주는 것 같습니다.

즉 이 메소드에서는 `false`를 리턴할 가능성이 아예 없을 것 같은데 리턴 타입을 void로 해주는건 어떨까요?

2021-09-04 14:25 UTC, f-lab-dev commented on src/main/java/com/yam/app/common/StringUtils.java
> +    public static boolean isBlank(String value) {
이거는 직접 구현하기보다는 외부 라이브러리도 있을 것 같습니다

2021-09-04 14:25 UTC, f-lab-dev commented on src/main/resources/mapper/xml/AccountCommandMapper.xml
> +    LIMIT 1
이거는 왜 넣어주신걸까요?

2021-09-04 15:38 UTC, JiwonDev commented on src/test/java/com/yam/app/account/domain/FakeAccountRepository.java
> +@Component
전혀 없습니다. 별 생각없이 적어놨었네요 바로 삭제했습니다. 지적 감사합니다👍

2021-09-04 15:39 UTC, JiwonDev commented on src/test/java/com/yam/app/account/domain/TokenVerifierTest.java
> +
넵 제거하겠습니다.

2021-09-04 15:41 UTC, JiwonDev commented on src/test/java/com/yam/app/account/infrastructure/MybatisAccountRepositoryTest.java
> +        account.completeRegister(); // boolean emailVerified = true
`completeRegister가 account객체의 값을 바꾼다는걸 모르지 않을까..?`
하는 생각에 살짝 적어놨던건데, 다시보니 제가 생각해도 바람직하지 않은 방법인 것 같습니다. 고치겠습니다. 감사합니다😊

2021-09-04 15:44 UTC, JiwonDev commented on src/test/java/com/yam/app/account/presentation/AccountCommandApiTests.java
> +            // Arrange
남겨두는게 조금 더 깔끔하지 않을까 살짝 고민했었는데, 지우는게 낫겠네요. 삭제하겠습니다✂

2021-09-04 19:03 UTC, JiwonDev commented on src/main/java/com/yam/app/account/domain/TokenVerifier.java
> +    public boolean verify(String token, String email) {
책임을 나누게 되면 토큰을 검증할 때, 가입 완료 처리할 때 같은 검색 쿼리가 2번 발생하기에 하나로 만드는 것이 낫겠다고 생각했었습니다.

그런데 리뷰 받으며 다시 보니 `토큰검증` 구현체가 바뀌었을 때 `가입완료` 처리 코드부분까지 영향을 끼치게 되어 좋지 않은 코드라고 생각됩니다.

그래서 리뷰를 반영하여 두 책임을 분리하였고, 인터페이스를 사용해 `토큰검증` 구현체와 의존성을 제거했습니다. 감사합니다😀

2021-09-04 19:06 UTC, JiwonDev commented on src/main/java/com/yam/app/account/domain/TokenVerifier.java
> +    public boolean verify(String token, String email) {
`즉 이 메소드에서는 false를 리턴할 가능성이 아예 없을 것 같은데 리턴 타입을 void로 해주는건 어떨까요?` 
반영해서 수정했습니다! 처음에 void와 boolean을 고민하다가, 그래도 성공했다는 확실한 값을 줘야되는게 아닐까 생각하여 true를 반환했었습니다. 그런데 멘토님 말씀대로 false가 반환 되는 경우가 아예 없으니 굳이 무언가를 반환해줄 필요가 없어보입니다. 감사합니다

2021-09-04 19:11 UTC, JiwonDev commented on src/main/java/com/yam/app/common/StringUtils.java
> +    public static boolean isBlank(String value) {
`org.apache.commons.lang3` 의존성을 추가해 `StringUtils.isBlank()`를 사용하도록 변경했습니다. 감사합니다😀

2021-09-04 19:33 UTC, JiwonDev commented on src/main/resources/mapper/xml/AccountCommandMapper.xml
> +    LIMIT 1
업데이트에서 LIMIT 1은 전혀 필요가 없지만, 쿼리문을 잘못 작성하더라도 전체 데이터가 변경되지 않도록 일종의 안전장치로 사용했습니다.

그런데 생각해보니 id로 업데이트를 하기에 굳이 이렇게 할 필요가 없어보입니다. [[Link]](https://stackoverflow.com/questions/5924115/using-limit-1-in-mysql) 처럼 확실한 이유가 있을 때 LIMIT를 사용하도록 하겠습니다.

2021-09-04 20:12 UTC, JiwonDev commented on src/main/java/com/yam/app/account/infrastructure/MybatisAccountRepository.java
> +        int result = template.update(COMMAND_NAMESPACE + "update", entity);
넵 해당 부분은 따로 PR을 만들어 전체적으로 고치도록 하겠습니다.😀

2021-09-04 22:17 UTC, Rebwon commented on src/main/java/com/yam/app/account/domain/VerifyAccountService.java
> +public class VerifyAccountService {
final 붙여주세요

2021-09-04 22:19 UTC, Rebwon commented on src/main/java/com/yam/app/account/infrastructure/MailTokenVerifier.java
> +public class MailTokenVerifier implements TokenVerifier {
토큰 검증을 인터페이스로 분리하고, 인프라 영역에서 DIP를 활용하도록 한 점 좋은 것 같아요👍👍👍

2021-09-04 22:21 UTC, Rebwon commented on src/main/java/com/yam/app/account/presentation/VerifyAccountRequest.java
> +    private String email;
여기서 NotBlank 검증이 가능하다면, 사실 apache commons를 추가해서 MailTokenVerifier에서 null check할 필요가 딱히 없어보이는데 어떻게 생각하시나요?

2021-09-04 22:24 UTC, Rebwon commented on src/test/java/com/yam/app/account/domain/TokenVerifierTest.java
> +    public static class MailTokenVerifierStub implements TokenVerifier {
MailTokenVerifier는 이미 구현이 되어 있는데 이걸 다시 만들 필요가 있을까요? 그리고 Stub이라고 하기엔 실제 구현에 가까운 행동을 하고 있네요.

2021-09-04 23:39 UTC, Rebwon commented on src/main/java/com/yam/app/account/domain/VerifyAccountService.java
> +    AccountRepository accountRepository;
접근 제어자 설정이 누락되었습니다.

2021-09-05 00:13 UTC, Rebwon commented on src/main/java/com/yam/app/account/presentation/AccountCommandApi.java
> +        @ModelAttribute VerifyAccountRequest request) throws Exception {
```@ModelAttribute``` 이걸 붙이지 않아도 아마 요청 파라미터 매핑이 되는 것으로 알고 있는데, 확인해본것은 아니라 확인 부탁드립니다.

2021-09-05 00:19 UTC, Rebwon commented on src/test/java/com/yam/app/account/domain/TokenVerifierTest.java
> +    void verify_email_and_token_correctly() throws Exception {
만약, 위에서 언급 했듯이 성급한 추상화라고 한다면 해당 케이스에 대한 검증은 도메인에서 하는 것이 맞지만 아니라면, TokenVerifier의 실제 구현은 인프라 영역에 있으므로 인프라 영역에서 테스트를 하시면 될 것 같습니다. 그리고 구현체를 테스트 더블로 써야하는 경우도 있지만 IO나 테스트 케이스를 만드는데 불편한 셋업 작업이 없는 구현이라면 실제 구현체로 테스트를 하시는게 맞습니다.

2021-09-05 03:08 UTC, Rebwon commented on src/main/java/com/yam/app/account/application/AccountFacade.java
> +    public void verify(VerifyAccountRequest request) {
registerConfirm()이 어떨까요?

2021-09-05 03:09 UTC, Rebwon commented on src/main/java/com/yam/app/account/domain/VerifyAccountService.java
> +    public void verify(VerifyAccountCommand command) {
이것도 registerConfirm()이 나아보이는데 어떠신가요?

2021-09-05 03:09 UTC, Rebwon commented on src/main/java/com/yam/app/account/presentation/AccountCommandApi.java
> +    public ResponseEntity<Void> verify(
요것도 verify 대신 registerConfirm

2021-09-05 07:06 UTC, JiwonDev commented on src/main/java/com/yam/app/account/domain/VerifyAccountService.java
> +public class VerifyAccountService {
`ConfirmRegisterAccountProcessor`로 변경했습니다. `verifyAccount`보다 훨씬 더 명확하네요😀

2021-09-05 07:39 UTC, JiwonDev commented on src/main/java/com/yam/app/account/infrastructure/MailTokenVerifier.java
> +public class MailTokenVerifier implements TokenVerifier {
`해당 구현체는 도메인에 있어도 낫다고 판단이 되는데`
- 제가 생각해도 저장소에서 이메일 토큰을 검증하는 객체는 인프라보다는 도메인 계층에 있는게 나아보입니다. 변경하겠습니다.✔

`섣부른 추상화를 사용한 것은 아닐까요?`
- 서비스 객체가 `TokenVerifier`의 구현체 정보를 알 필요가 없다고 생각했습니다.
- 물론 `TokenVerifier는 구현체가 바뀔일이 없는데 굳이 인터페이스로 추상화할 필요가 있을까..?`
  라는 고민을 했었는데 반대로 생각해서 추상화 해서 생기는 성능 이유나 단점이 딱히 없다고 생각했습니다. 그래서 만약 토큰검증 구현체가 교체되더라도 변경이 전파되지 않도록 추상화하여 만드는게 맞다고 판단했습니다.

final은 까먹고 있었네요. 말씀대로 IntelliJ 템플릿 설정을 변경했습니다. 감사합니다 👍

2021-09-05 07:44 UTC, JiwonDev commented on src/main/java/com/yam/app/account/presentation/VerifyAccountRequest.java
> +    private String email;
Request는 변경될 가능성이 있다고 생각했습니다.
도메인 계층이 프레젠테이션 계층에 의존성이 있는 건 좋지 못한 설계이기에 Request의 검증 여부와 상관없이 `MailTokenVerifier`에서 추가적인 null check가 필요하다고 생각하였습니다.😀

2021-09-05 07:51 UTC, Rebwon commented on src/main/java/com/yam/app/account/presentation/VerifyAccountRequest.java
> +    private String email;
지금 현재 구조는 Request를 받아서 toCommand로 변경하는데 이때 NPE가 발생하지 실제 도메인 계층까지 NPE가 발생하진 않을 것 같아서, apache commoms라는 외부 의존성을 도메인 계층에서 사용해야 하는가에 대한 의문점입니다.

2021-09-05 07:51 UTC, JiwonDev commented on src/test/java/com/yam/app/account/domain/TokenVerifierTest.java
> +    public static class MailTokenVerifierStub implements TokenVerifier {
`불편한 셋업 작업이 없는 구현이라면 실제 구현체로 테스트를 하시는게 맞습니다.`
아래에서 말씀하신 것처럼 다시 만들 필요가 없는 것 같습니다. 반영하겠습니다. 감사합니다👍

2021-09-05 07:58 UTC, JiwonDev commented on src/main/java/com/yam/app/account/presentation/AccountCommandApi.java
> +        @ModelAttribute VerifyAccountRequest request) throws Exception {
어노테이션을 생략하더라도 Argument Resolver에서 아래와 같이 동작합니다.
- 단순타입(String, int, Integer)는 @RequestParam 사용한 것과 동일하게 작동
- 그 외 타입들은 @ModelAttribute 사용한 것과 동일하게 작동

하지만 다 생략하고 파라미터만 적어버리면 혼동할 여지가 있어 명시적으로 적어주는게 맞다고 판단했습니다.

2021-09-05 08:00 UTC, JiwonDev commented on src/main/java/com/yam/app/account/domain/VerifyAccountService.java
> +    AccountRepository accountRepository;
넵 수정하겠습니다.✔

2021-09-05 08:02 UTC, JiwonDev commented on src/test/java/com/yam/app/account/domain/TokenVerifierTest.java
> +    void verify_email_and_token_correctly() throws Exception {
TokenVerifier 구현체를 도메인영역으로 옮겼습니다.

`위에서 언급 했듯이 성급한 추상화라고 한다면` 는
추상화 해서 생기는 성능 이유나 단점이 딱히 없다고 생각했습니다. 그래서 만약 토큰검증 구현체가 교체되더라도 변경이 전파되지 않도록 추상화하여 만드는게 맞다고 판단했습니다.

2021-09-05 08:05 UTC, JiwonDev commented on src/main/java/com/yam/app/account/application/AccountFacade.java
> +    public void verify(VerifyAccountRequest request) {
`TokenVerifier`를 제외하고 나머지 영역에서 `verify`를 `registerConfirm`으로 더 명확한 의미를 가지도록 변경했습니다. 감사합니다😊

2021-09-05 08:06 UTC, JiwonDev commented on src/main/java/com/yam/app/account/domain/VerifyAccountService.java
> +    public void verify(VerifyAccountCommand command) {
넵 같이 변경하겠습니다.

2021-09-05 08:06 UTC, JiwonDev commented on src/main/java/com/yam/app/account/presentation/AccountCommandApi.java
> +    public ResponseEntity<Void> verify(
👍

2021-09-05 08:07 UTC, Rebwon commented on src/test/java/com/yam/app/account/domain/TokenVerifierTest.java
> +    void verify_email_and_token_correctly() throws Exception {
자바에서는 invokeinterface 즉, 인터페이스 변수를 선언하여 해당 메서드를 실행하는 것은 class loading의 verification 작업이 굉장히 비싼 연산을 수행하게 됩니다. 따라서 일반 클래스를 사용한 invokevirtual이 훨씬 성능 상 이점이 있습니다.

추상화 역시도 트레이드 오프이며, 성능에 영향을 미치는 중요한 작업이므로 추상화를 고려할 땐 정말 신중하게 판단해주시면 좋을 것 같습니다.

2021-09-05 08:59 UTC, JiwonDev commented on src/main/java/com/yam/app/account/presentation/VerifyAccountRequest.java
> +    private String email;
`ConfirmRegisterAccountProcessor (이전의 VerifyAccountService)`에서는 그렇지만, `MailTokenVerifier`는 범용적인 서비스이니 다른 곳에서 사용된다고 가정하면 null check를 보장해줄 수 없다고 판단했습니다.

다만 `apache commoms`라는 외부 의존성이 도메인에 추가가 되어서, `MailTokenVerifier`의 위치는 인프라가 맞는건가..?하는 고민이 있습니다.

TokenVeirifer는 범용적인 기능이라고 생각해서 추상화 했던 것인데, 이게 나쁜 추상화가 아니었는지 다시한번 공부해봐야겠습니다. 감사합니다😊

2021-09-05 09:06 UTC, Rebwon commented on src/main/java/com/yam/app/account/presentation/VerifyAccountRequest.java
> +    private String email;
외부 의존성이 도메인에 있는 것은 바람직하진 않습니다. 그리고 사실 null 체크 정도는 스프링의 Assert 클래스를 사용해도 충분히 할 수 있고 오히려 더 좋지만, 그렇게 하지 않는 이유는 외부 의존성으로부터의 격리가 목적이기 때문입니다. 그리고 TokenVerifier을 외부에서 사용하더라도 파라미터에 값을 넘기기 전에 null check를 해주는 방법도 있다고 생각합니다.

2021-09-05 09:30 UTC, JiwonDev commented on src/test/java/com/yam/app/account/domain/TokenVerifierTest.java
> +    void verify_email_and_token_correctly() throws Exception {
아 클래스와 인터페이스가 성능 차이가 있다는 걸 몰랐었네요. 위에서 언급해주신 내용과 더불어 더더욱 TokenVerifier 를 추상화할 필요는 없어보입니다.

또한 null체크를 하는데 굳이 외부 의존성을 추가해서 인프라 영역으로 분리할 필요는 없어보이구요.

새로운 커밋을 하나 더 만들어 도메인 계층에 인터페이스가 아닌 TokenVerifier 클래스를 만들고, 외부 의존성을 사용하지 않도록 변경하겠습니다. 

정말 저에게 스스로에게 도움이 많이 되는 리뷰였습니다. 정말 감사합니다👏

2021-09-05 21:34 UTC, Rebwon commented on src/main/java/com/yam/app/account/domain/TokenVerifier.java
> +        if (!account.isValidToken(token)) {
TokenVerifier가 막상 ConfirmRegisterAccountProcessor를 만드니까, 할일이 없어지는거 같은건 저만 그런가요? account.isValidToken()으로 토큰 검증을 여기서 해버리니까 TokenVerifier는 필요가 없어지는 것 같기도 하구요... 여기서 그리고 Reader를 사용해서 조회하고 ConfirmRegisterAccountProcessor에서도 또 Reader를 사용해서 조회한 다음에 update 이후 또 내부적으로 findByEmail() 조회를 하면 등록 확인 메서드에서 조회만 3번 일어나다보니까 성능상 문제가 될 것 같기도 하구요...

2021-09-05 21:34 UTC, Rebwon commented on src/main/java/com/yam/app/account/domain/ConfirmRegisterAccountProcessor.java
> +public class ConfirmRegisterAccountProcessor {
final 누락됬습니다.

2021-09-05 21:34 UTC, Rebwon commented on src/main/java/com/yam/app/account/application/ConfirmRegisterAccountCommand.java
> +public class ConfirmRegisterAccountCommand {
final 누락되었어요

2021-09-05 22:51 UTC, JiwonDev commented on src/main/java/com/yam/app/account/domain/TokenVerifier.java
> +        if (!account.isValidToken(token)) {
말씀하신 것처럼 여러번 Account를 조회하게되어 성능에 문제가 생길 수 있습니다.

다만 제 생각은
- 이메일 검증은 회원 가입시에만 사용되어 다른 요청에 비해 자주 발생하는 요청이 아닙니다.
- 토큰검증 방식은 프로젝트가 진행되며 바뀔 가능성이 있다고 생각해서 `TokenVerifier`로 책임을 분리했었습니다. 이 경우에는 `account.isValidToken()`이외에 추가적인 동작을 할 수도 있습니다.
- 의존성만 분리해두고 어느 정도 개발이 완료되고 나서 성능이나 발생할 문제에 대해 다시 고민해도 괜찮다고 생각했습니다.

2021-09-05 22:52 UTC, JiwonDev commented on src/main/java/com/yam/app/account/domain/ConfirmRegisterAccountProcessor.java
> +public class ConfirmRegisterAccountProcessor {
IntelliJ 템플릿만 바꿔놓고, 기존에 수정한 객체들은 final확인을 안했었네요. 바로 바꾸겠습니다. 감사합니다👍

2021-09-05 22:53 UTC, JiwonDev commented on src/main/java/com/yam/app/account/application/ConfirmRegisterAccountCommand.java
> +public class ConfirmRegisterAccountCommand {
넵 수정하겠습니다‼ 앞으로는 final 안붙이는 실수는 없도록 하겠습니다.😂

2021-09-05 23:12 UTC, Rebwon approved these changes

2021-09-07 04:52 UTC, merged