ADD Login HTTP API
f-lab-edu/YouAndMe pull request #32
Opened 2021-09-07 09:41 UTC by JiwonDev

#9 Resolves.

2021-09-07 10:58 UTC, Rebwon requested changes
Login하는 행위 자체는 Query보다는 Command에 가까운데 Query API로 하신 이유가 있을까요?

2021-09-07 10:58 UTC, Rebwon commented on src/main/java/com/yam/app/account/presentation/AccountQueryApi.java
> +    @PostMapping("/api/login")
/api/accounts/login이 좋아보입니다.

2021-09-07 12:22 UTC, JiwonDev commented on src/main/java/com/yam/app/account/presentation/AccountQueryApi.java
> +    @PostMapping("/api/login")
넵 `/api/accounts/login`로 수정하겠습니다.👍

Login 행위는 분명 Command에 가깝긴한데, 실제 동작은 데이터를 수정하는게 아니라 단순 조회만 하기에 Query로 보는 것이 맞다고 판단했습니다.

이와 관련된 내용을 찾아보는 와중에 [저와 비슷한 생각을 가진 스택오버플로우 질문](https://stackoverflow.com/questions/13798739/cqrs-and-session)에 대한 답변을 봤었는데, CQRS를 억지로 세션 로그인에 적용하는 것 자체가 좋지 못한 케이스라고 합니다.

그래서 로그인, 회원가입은 다시 이름을 RegisterApi, LoginApi로 바꿔야하나 고민중에 있습니다🤣

2021-09-07 13:12 UTC, Rebwon commented on src/main/java/com/yam/app/account/presentation/AccountQueryApi.java
> +    @PostMapping("/api/login")
마틴 파울러도 pop() 연산을 예로 들면서 명령 책임과 조회 책임이 명확하게 분리되지 않는 케이스도 있다고 했었죠. 다만 현재는 Login 행위가 단순 세션 기반일지라도 추후 토큰 기반, OAuth 제공자 기반으로 변경될 여지도 있다고 생각합니다. 그래서 이 부분은 고민을 좀 해보면 좋을거 같아요.

2021-09-08 02:15 UTC, Rebwon commented on src/main/java/com/yam/app/account/domain/LoginAccountProcessor.java
> +        var account = accountReader.findByEmail(toCommand.getEmail());
이 부분은 orElseThrow로 null이나 empty 여부를 바로 확인 가능할 것 같습니다.

2021-09-08 02:16 UTC, Rebwon commented on src/main/java/com/yam/app/account/domain/LoginAccountProcessor.java
> +        if (!matches) {
굳이 boolean으로 변수를 빼야할 이유가 있나요? 인라인 처리로 하는게 좋아 보이는 것 같습니다.

2021-09-08 02:19 UTC, Rebwon commented on src/test/java/com/yam/app/account/presentation/AccountQueryApiTest.java
> +        @DisplayName("이메일과 비밀번호가 유효하지않아 로그인에 실패한 경우 401 에러를 반환한다.")
이메일 형식과 비밀번호 형식도 검증 논리 테스트가 하나 더 추가되면 좋겠습니다.

2021-09-08 02:22 UTC, Rebwon reviewed
이미 이슈로 작업 단위를 잘개 쪼갰는데, 도메인, 애플리케이션 로직과 개체가 필요한 작업인지 의문이 듭니다. 어떻게 생각하시나요?

2021-09-08 05:22 UTC, JiwonDev commented on src/main/java/com/yam/app/account/domain/LoginAccountProcessor.java
> +        if (!matches) {
변수를 분리하는 것이 코드를 이해하기에 더 좋다고 생각했습니다.

또한 if (methodA.call() || methodB.call()) 이런 경우, 앞에 메서드에서 True가 나오면 뒤에 메서드가 실행되지 않아서 메서드를 2개 이상 사용하면 버릇처럼 변수로 받아 사용 했었습니다.

그런데 여기에서는 인라인으로 처리하는게 더 깔끔해 보이네요. 수정하겠습니다 감사합니다😀

2021-09-08 07:16 UTC, JiwonDev commented on src/test/java/com/yam/app/account/presentation/AccountQueryApiTest.java
> +        @DisplayName("이메일과 비밀번호가 유효하지않아 로그인에 실패한 경우 401 에러를 반환한다.")
넵 추가했습니다 ✔

2021-09-08 07:29 UTC, Rebwon commented on src/main/java/com/yam/app/account/domain/LoginAccountProcessor.java
> +            passwordEncrypter.encode(password))) {
인코딩해서 저장한 패스워드를 다시 인코딩할 이유는 없어보입니다.

2021-09-08 07:30 UTC, Rebwon commented on src/main/java/com/yam/app/account/presentation/AccountQueryApi.java
> +        // SessionUtils.setLoginAccountEmail(session, request.getEmail());
세션 구현이 당장 필요없는 작업이라면 주석을 지우시는게 좋아보입니다.

2021-09-08 07:30 UTC, Rebwon commented on src/main/java/com/yam/app/account/presentation/AccountQueryApi.java
> +        HttpSession session) {
세션도 현재 파라미터로 필요하진 않은 것 같습니다

2021-09-08 07:40 UTC, JiwonDev commented on src/main/java/com/yam/app/account/domain/LoginAccountProcessor.java
> +            passwordEncrypter.encode(password))) {
제가 어이없는 실수를 했네요🤣
`if (!passwordEncrypter.matches(toCommand.getPassword(), password))`로 변경하겠습니다.

2021-09-08 07:40 UTC, JiwonDev commented on src/main/java/com/yam/app/account/presentation/AccountQueryApi.java
> +        // SessionUtils.setLoginAccountEmail(session, request.getEmail());
넵 삭제하겠습니다.

2021-09-08 07:40 UTC, JiwonDev commented on src/main/java/com/yam/app/account/presentation/AccountQueryApi.java
> +        HttpSession session) {
넵 삭제하겠습니다.

> 이미 이슈로 작업 단위를 잘개 쪼갰는데, 도메인, 애플리케이션 로직과 개체가 필요한 작업인지 의문이 듭니다. 어떻게 생각하시나요?

한 PR에 추가되는 코드가 너무 작다고 생각되어 한번에 묶어서 작업했었습니다.
그런데 다시 생각해보니 유즈케이스와 이슈를 나눈 의미가 없어지네요.
다음 작업부터는 이슈에 적인 작업 단위로 코드를 작성하겠습니다. 지적 해주셔서 감사합니다👍

2021-09-08 07:57 UTC, Rebwon commented on src/main/java/com/yam/app/account/domain/LoginAccountProcessor.java
> +        final String password = account.orElseThrow(IllegalStateException::new).getPassword();
변수를 이렇게 따로 빼내는 것이 좋은 경우가 있지만 대부분은 인라인 처리하는게 좋습니다. Command의 패스워드와 Account의 패스워드라고 파라미터 입력부에서 직관적으로 볼 수 있으니까요.

'''java
if(passwordEncrpter.matches(toCommand.getPassword(), account.getPassword()) {
    throw new IllegalStateException();
}
'''

2021-09-08 07:59 UTC, Rebwon commented on src/main/java/com/yam/app/account/presentation/AccountQueryApi.java
> +        @Validated @RequestBody LoginAccountRequest request) {
Validated가 아니라 Valid 아닌가요?

2021-09-08 08:00 UTC, Rebwon commented on src/main/java/com/yam/app/account/presentation/RegisterAccountRequest.java
> +        message = "비밀번호는 영어와 숫자, 특수문자로 8~12자리 이내로 입력해주세요.")
회원가입 쪽에 이렇게 변경해주셨으면, 해당 개체를 사용하는 테스트 코드 쪽에도 검증 로직을 반영해주세요.

2021-09-08 08:03 UTC, JiwonDev commented on src/main/java/com/yam/app/account/presentation/AccountQueryApi.java
> +        @Validated @RequestBody LoginAccountRequest request) {
스프링에서 제공해주는 어노테이션이 `@Validated`이고
자바에서 표준으로 제공해주는 어노테이션이 `@Valid`로 알고있습니다.

그래서 @Valid를 스프링에서 사용하려면
`implementation 'org.springframework.boot:spring-boot-starter-validation'` 의존성을 추가해주어야합니다.

당연히 동작은 같으므로, 성능상의 차이는 없지만 스프링에서 만든 `@Validated`가 조금 더 다양한 사용법을 제공해준다고 알고있습니다.

2021-09-08 08:07 UTC, JiwonDev commented on src/main/java/com/yam/app/account/presentation/RegisterAccountRequest.java
> +        message = "비밀번호는 영어와 숫자, 특수문자로 8~12자리 이내로 입력해주세요.")
거기까진 생각하지 못했네요. 회원가입 검증 테스트 로직도 변경하도록 하겠습니다.😀

2021-09-08 08:09 UTC, JiwonDev commented on src/main/java/com/yam/app/account/domain/LoginAccountProcessor.java
> +        final String password = account.orElseThrow(IllegalStateException::new).getPassword();
여기에는 상관없지만
`if(methodA || methodB)` 의 경우 methodB가 실행되지 않아서 디버깅에 애먹었던 경험이 있습니다.
그래서 성능에 영향을 끼치는 경우가 아니라면, 최대한 변수로 분리해서 사용하려고 하는데

말씀 들어보니 인라인이 더 직관적이고 좋겠네요. 변경하도록 하겠습니다😀

2021-09-08 08:43 UTC, Rebwon commented on src/main/java/com/yam/app/account/presentation/AccountQueryApi.java
> +        @Validated @RequestBody LoginAccountRequest request) {
기존에 Valid로 작성된 코드와 일관성이 떨어집니다. 만약 Validated가 더 좋고 동작에 문제가 없다면, 다른 코드도 다 변경하는게 맞지 않을까요? 그리고 Valid가 좀 더 일반적인 애너테이션이고, Validated가 스프링 Validation 라이브러리를 추가해야만 사용할 수 있는 애너테이션이 아닌가요?

2021-09-08 08:54 UTC, JiwonDev commented on src/main/java/com/yam/app/account/presentation/AccountQueryApi.java
> +        @Validated @RequestBody LoginAccountRequest request) {
제가 말을 애매하게 적었는데
>Validated가 스프링 Validation 라이브러리를 추가해야만 사용할 수 있는 애너테이션이 아닌가요?

맞습니다. 다만 해당 의존성을 추가하지 않으면 자바 JSR-303표준인 `@Valid`가 스프링의 Validator로 동작하지 않는다는 의미였습니다.


혹시나 해서 [스프링 공식 문서](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/validation/annotation/Validated.html)를 찾아봤는데 편의성을 위해 둘 다 지원하는거지 동작에는 아무런 차이가 없다고 합니다.

> 기존에 Valid로 작성된 코드와 일관성이 떨어집니다. 만약 Validated가 더 좋고 동작에 문제가 없다면, 다른 코드도 다 변경하는게 맞지 않을까요?

다만 말씀하신 것처럼 일관성을 맞추기 위해서 `@Valid`로 적고, 검증 그룹핑 추가 기능이 필요할 때만 `@Validated`를 사용하도록 하겠습니다.😀

2021-09-08 09:25 UTC, Rebwon commented on src/main/java/com/yam/app/account/domain/LoginAccountProcessor.java
> +            account.orElseThrow(IllegalStateException::new).getPassword())) {
orElseThrow절을 위에 var 선언부에서 끝내주세요. 코드 가독성이 떨어집니다.

2021-09-08 09:29 UTC, JiwonDev commented on src/main/java/com/yam/app/account/domain/LoginAccountProcessor.java
> +            account.orElseThrow(IllegalStateException::new).getPassword())) {
넵 바로 수정하겠습니다.

2021-09-08 09:39 UTC, Rebwon approved these changes

2021-09-08 09:39 UTC, merged